### PR TITLE
Multiple Accounts Save Contact (Android)

### PR DESCRIPTION
**Pull request by comporell**
Added option to save a contact to a known account on Android. Is it the best way to do this?

### CODE REVIEW

**Comment by mrpaaske** [comment]
@firescript, this is a much needed feature, but could we make it even more advanced where we could have an API getAccounts() and extend save() with account  Contact.save(account)?

**Comment by firescript** [comment]
@comporell @fpaaske - are we safe to merge this? let me know.

**Comment by dlcole** [comment]
I’ll test this later this evening.

**Comment by comporell** [comment]
> 
> 
> @comporell @fpaaske @dlcole - are we safe to merge this? let me know.

nope it is not safe. After having strange issues that break the contact list, I decided to change my logic and implemented https://github.com/rapidwebltd/php-google-contacts-v3-api instead.

**Comment by firescript** [comment]
@comporell - ok are you planning on fixing the PR? Or should I just close this one up and NOT merge it.

**Comment by comporell** [comment]
> 
> 
> @comporell - ok are you planning on fixing the PR? Or should I just close this one up and NOT merge it.

Hello, please close this and do not merge it. Would be better if someone else tried it from scratch. I had lots of issues with it which eventually lead to lots of lost contacts on a phone with 4 accounts.

**Pull request closed without merging**
