### PR TITLE
Fix #33

### LINKED ISSUE #33: AOT  Build issue: contacts Could not find module './get-all-contacts-worker.js
the plugin is working fine in the normal release build mode but when we build in the AOT release mode the app crashes can you please look at the below error messages 

JS ERROR Error: Could not find module './get-all-contacts-worker.js'. Computed path '/var/mobile/Containers/Data/Application/2896D048-EF2B-4A21-ABDF-E08EF46154E9/Library/Application Support/LiveSync/app/get-all-contacts-worker.js'.
JS ERROR TypeError: console.dump is not a function. (In 'console.dump(e)', 'console.dump' is undefined)

kindly help us

### PR DESCRIPTION
**Pull request by nickykln**
Hello, 
I fixed this issue while compiling with Web Pack. #33 

Nicolas

### CODE REVIEW

**Comment by firescript** [comment]
Thanks @nickykln can you explain what is different here? I just went through it. Was hard to notice anything different besides formatting changes. Please just let me know where you made changes.

**Comment by nickykln** [comment]
Hi @firescript 

Sorry for the formatting differences.

Actually I just implemented the fix explained by 
[DeepakArora76](/DeepakArora76) in the comment of #33 

Replace the following lines in the files index.ios.js and index.andriod.js

> exports.getAllContacts = function(contactFields) {
> return new Promise(function (resolve, reject) {
> var worker = new Worker('./get-all-contacts-worker.js');

> exports.getAllContacts = function(contactFields) {
> return new Promise(function (resolve, reject) {
> var worker;
> // Check if webpack is used, in which case, load using webpack loader, otherwise load using relative path
> // Using webpack assumes that the nativescript worker loader is properly configured. See https://github.com/NativeScript/worker-loader
> if (global["TNS_WEBPACK"]) {
> var myWorker = require('nativescript-worker-loader!./get-all-contacts-worker.js');
> worker = new myWorker();
> } else {
> worker = new Worker('./get-all-contacts-worker.js'); // relative for caller script path
> }

Do you want me to make another pull request or you prefer to do it yourself ?

Thanks,

Nicolas

**Comment by nickykln** [comment]
Hi @firescript, 

Did you have time to review this pull request ?
Let me know if you want me to clear the formating issue ?

thnaks,

Nicolas

**Comment by jbsnt16** [comment]
Who is this?

**Comment by jbsnt16** [comment]
Why do you keep sending me emails? Have I been hacked?

Nicole.  707-365-3923

**Comment by jbsnt16** [comment]
Hello,

Can you please take me off your mailing list?

Thank you.
Nicole.

**Comment by firescript** [comment]
thanks @nickykln

**Pull request merged**
